site_name: Chathumal Madhuranga

theme:
  name: 'material'
  logo: images/logo.png
  features:
      - header.autohide

  palette:
    - scheme: default
      primary: blue
      accent: blue
      #toggle:
      #  icon: material/toggle-switch-off-outline
      #  name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      #toggle:
      #  icon: material/toggle-switch
      #  name: Switch to light mode

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Google Sans
    code: Regular
  favicon: images/logo.png

markdown_extensions:
  - attr_list

# Page tree
nav:
  - Home: index.md
  - About me: aboutme.md
  - Resume: resume.md 
  - Portfolio:
    - Disaster Response: portfolio/disaster.md
    - Environment Monitoring: portfolio/environment.md
    - Surveying and Mapping: portfolio/surveying.md
    - Capacity Building: portfolio/capacitybuilding.md
    - Extra Activities: portfolio/extra.md
  - Projects Involved: projects.md
  - Research & Publications: research.md
  - Contact: contact.md
  




# Options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chathumal93
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/chathumal93
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/chathumal-madhuranga/

# Copyright
copyright: 'Copyright &copy; 2023 Chathumal Madhuranga'